development:
  adapter: mysql2
  host: localhost
  database: drafter_development
  username: root

test:
  adapter: mysql2
  host: localhost
  database: drafter_test
  username: root

production:
  adapter: mysql2
  host: localhost
  database: drafter_production
  username: root